import fs from "node:fs";
import path from "node:path";
import type { Topic, TopicHeader, SubjectId } from "./types";
import { SUBJECT_IDS } from "./subjects";

/**
 * Server-only content loader. Topics live as JSON files under
 *   <project root>/content/<subjectId>/<topicId>.json
 * generated by the content pipeline. Reading happens at request/build time.
 */

const CONTENT_DIR = path.join(process.cwd(), "content");

type Cache = { topics: Map<string, Topic[]>; mtime: number };
const g = globalThis as unknown as { __studyhubCache?: Cache };

function readSubjectTopics(subjectId: SubjectId): Topic[] {
  const dir = path.join(CONTENT_DIR, subjectId);
  let files: string[] = [];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));
  } catch {
    return [];
  }
  const topics: Topic[] = [];
  for (const f of files) {
    try {
      const raw = fs.readFileSync(path.join(dir, f), "utf8");
      const t = JSON.parse(raw) as Topic;
      if (t && t.id && t.title) topics.push({ ...t, subjectId });
    } catch (e) {
      console.warn(`[content] failed to parse ${subjectId}/${f}:`, e);
    }
  }
  topics.sort((a, b) => (a.order ?? 0) - (b.order ?? 0) || a.title.localeCompare(b.title));
  return topics;
}

function loadAll(): Map<string, Topic[]> {
  // In dev we re-read on every request so freshly generated content shows up.
  if (process.env.NODE_ENV === "production" && g.__studyhubCache) {
    return g.__studyhubCache.topics;
  }
  const topics = new Map<string, Topic[]>();
  for (const id of SUBJECT_IDS) topics.set(id, readSubjectTopics(id));
  g.__studyhubCache = { topics, mtime: Date.now() };
  return topics;
}

export function getSubjectTopics(subjectId: SubjectId): Topic[] {
  return loadAll().get(subjectId) ?? [];
}

function toHeader(t: Topic): TopicHeader {
  return {
    id: t.id,
    subjectId: t.subjectId,
    title: t.title,
    summary: t.summary,
    order: t.order,
    group: t.group,
    estMinutes: t.estMinutes,
    counts: {
      sections: t.sections?.length ?? 0,
      flashcards: t.flashcards?.length ?? 0,
      quiz: t.quiz?.length ?? 0,
      exercises: t.exercises?.length ?? 0,
    },
  };
}

export function getTopicHeaders(subjectId: SubjectId): TopicHeader[] {
  return getSubjectTopics(subjectId).map(toHeader);
}

export function getTopic(subjectId: SubjectId, topicId: string): Topic | null {
  return getSubjectTopics(subjectId).find((t) => t.id === topicId) ?? null;
}

export function getAllTopics(): Topic[] {
  return SUBJECT_IDS.flatMap((id) => getSubjectTopics(id));
}

export interface SubjectStat {
  topics: number;
  sections: number;
  flashcards: number;
  quiz: number;
  exercises: number;
}

export function getSubjectStat(subjectId: SubjectId): SubjectStat {
  const ts = getSubjectTopics(subjectId);
  return ts.reduce<SubjectStat>(
    (acc, t) => ({
      topics: acc.topics + 1,
      sections: acc.sections + (t.sections?.length ?? 0),
      flashcards: acc.flashcards + (t.flashcards?.length ?? 0),
      quiz: acc.quiz + (t.quiz?.length ?? 0),
      exercises: acc.exercises + (t.exercises?.length ?? 0),
    }),
    { topics: 0, sections: 0, flashcards: 0, quiz: 0, exercises: 0 },
  );
}
